apiVersion: v2
name: onion-gen
description: A fleet searching for Tor Onion Service v3 vanity addresses
type: application
version: 0.1.0
appVersion: "0.1.0"
home: https://github.com/mihalych-pro/onion-gen
keywords:
  - tor
  - onion
  - vanity-address
