apiVersion: v1
kind: Service
metadata:
  name: {{ include "onion-gen.fullname" . }}-master
  labels:
    {{- include "onion-gen.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - name: http
      port: {{ .Values.master.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "onion-gen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: master
